name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO111MODULE: on

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18]
    name: Test @ Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Tests
        run: |
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...
      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.18 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action
